// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam/test/api_layer/data_source/get_all_subjects_ds_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam/api_layer/api_service/api_service.dart' as _i3;
import 'package:online_exam/api_layer/models/response/subjects_response.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubjectsResponse_0 extends _i1.SmartFake
    implements _i2.SubjectsResponse {
  _FakeSubjectsResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SubjectsResponse> getSubjects({
    int? limit = 7,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubjects,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue:
            _i4.Future<_i2.SubjectsResponse>.value(_FakeSubjectsResponse_0(
          this,
          Invocation.method(
            #getSubjects,
            [],
            {
              #limit: limit,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.SubjectsResponse>);
}
